### ISSUE TITLE
Interactions sur smartphone

### ISSUE THREAD

**Issue by BrunoSpy** [BrunoSpy/olcc#1]
Sur smartphone l'absence de hover ainsi que la taille des doigts de certains nécessitent de repenser certaines interactions.

Voici les actions à prendre en compte :
1. Comment activer le highlight ?
2. Comment afficher un totoz ?
3. Comment répondre à un post ?

Les interactions à disposition : 
1. Tap
2. Double tap
3. Appui long
4. Swipe

Je propose : 
- [x] Highlight : tap sur tout le post
- [x] Afficher totoz : tap sur le totoz
- [ ] Répondre (inclusion de la norloge dans le champ) : double tap sur tout le post

A discuter.

**Comment by dguihal** [comment]
Etant donné que tu peux avoir plusieurs horloges par post ta proposition 1 ne tient pas tel quel

Par contre on pourrait imaginer une extension ou tu tap sur le post pour le hightlight de la 1° horloge et un swipe pour la suivante/précédente

**Comment by dguihal** [comment]
Quand on totoz je pencherais plus pour un appui long qui déclenche l'affichage et qui disparait lors de l'arrêt de l'appui

**Comment by claudex** [comment]
1: Un tap sur le post peut highlighté toutes norloges référencées par le post, ça ne me choque pas plus que ça.
2: Un appuie long qui disparaît quand on appuie c'est pénible, parce qu'on se retrouve avec un doigt au milieu d'écran qui cache le totoz. Je préfère un tap ou un appuie long sur le totoz.
3: Je dirais qu'un appuie sur la norloge du post déclenche le répondre. Parce que sinon, ça risque trop d'arriver par erreur en tapant sur un post.

**Comment by ckillerz** [comment]
# innovation here.

à la sélection du texte d'un post, tu fais apparaitre une mini toolbar sous le post avec les icones "répondre" et autres fonctions imaginables genre : 
- le highlight
- un bouton ♥ pour poster un message ++++++++++
- un bouton "citation" 
  ...

un raccourci  pour le highligt serait de sélectionner la nhorloge du post.

pour les totoz, un tap sur [:nomtotoz] fait apparaitre le totoz évidement
