### ISSUE TITLE
Rendre le post pessimiste

### ISSUE THREAD

**Issue by n-e** [BrunoSpy/olcc#2]
Fonctionnement actuel : quand on poste le champ de post est immédiatement effacé sans attendre le résultat de la requête

Problème : si la requête de post échoue le message est perdu et il faut le retaper

Fonctionnement souhaité : Effacer le post seulement une fois que la requête réussie.
Eventuellement, en + : afficher un spinner tant que la requête est en cours, l'effacer quand la requête réussit, afficher une icone d'erreur quand la requête échoue

**Comment by ckillerz** [comment]
Pourquoi uniquement le dernier ?

l'idéal, ca serait de pouvoir naviguer dans l'historique de ces posts et pouvoir les rééditer ou changer de tribune de destination avant le repost

**Comment by n-e** [comment]
Ça m'a l'air un peu overkill non ?

**Comment by BrunoSpy** [comment]
@ckillerz c'est clairement pas du tout la même friture
