### ISSUE TITLE
Gérer les norloges complètes yyyy-MM-ddTHH:mm:ss

### ISSUE THREAD

**Issue by ghost** [BrunoSpy/olcc#43]
Gérer le format de norloge complet yyyy-MM-ddTHH:mm:ss dans les cas suivants:

- pour l'affichage, le highlight des posts reçus depuis les backends.
- lorsque l'on clique sur une norloge d'un jour différent (recommandation: remplacer l'horrible format non standard MM/dd#HH:mm:ss).

**Comment by ghost** [comment]
A implémenter ASAP!

**Comment by BrunoSpy** [comment]
cf 291ebfa4d83fc4793f2bd7a9a9e553a817cb0397
