### ISSUE TITLE
Gérer les backends TSV

### ISSUE THREAD

**Issue by ghost** [BrunoSpy/olcc#44]
Un backend TSV :

1. est encodé en UTF-8
2. est servi en text/tab-separated-values
3. a des tags qui ne sont PAS XML-encodés
4. n'a pas d'entête
5. a deux formats possibles: avec ou sans login

Format avec login pour les tribunes gérant l'authentification:

 ${id}\t${time}\t${info}\t${login}\t${message}\n

Format sans login pour les autres:

 ${id}\t${time}\t${info}\t${message}\n

**Comment by dguihal** [comment]
Le seul vrai format est
${id}\t${time}\t${info}\t${login}\t${message}\n
Sachant que le champ login peut être vide, mais ça ne change rien au format

**Comment by ghost** [comment]
Oh non on va perdre un octet!
